CLASS zcl_zodata_user_pwd_ap_dpc_ext DEFINITION
  PUBLIC
  INHERITING FROM zcl_zodata_user_pwd_ap_dpc
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_ZODATA_USER_PWD_AP_DPC_EXT IMPLEMENTATION.
ENDCLASS.
