CLASS zcx_email_send_fail DEFINITION
INHERITING FROM cx_static_check
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCX_EMAIL_SEND_FAIL IMPLEMENTATION.
ENDCLASS.
